### ISSUE TITLE
FLY WITHOUT OP

### ISSUE THREAD

**Issue by ghost** [iiFlamiinBlaze/BlazinFly#18] opened 2020-04-27 12:44 UTC
If i say true, i don't know how fly without OP, i wrote the permissions but just say me I don't have permissions. Just function with OP. Fix it pls.

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 12:58
Send me the list of plugins on your server by doing /plugins in game.

**Comment by ghost** [comment] 2020-04-27 13:27
EconomyAPI v5.7.2, AutoClearLagg v3.0.1, WorldProtect v2.3.8, UltraCapes v1.7.5, Hotbar v2.0.3, PurePerms v1.4.3, StaffMode v1.1.0, CustomShopUI v4.0.5, WorldGuard v1.1.1, NoHungerLoss v1.0.0, CPS v1.0.0, KillMoney v2.1.0, KDR v1.0.0, EasyCommandAutofill v1.0.1, MSpawns v2.2, MyPlot v1.6.14, essentialsTP v1.2.2, PiggyCrates v2.0.6, MultiWorld v1.5.2, ParticleX v1.0.0, CustomAlerts v2.1, SimpleWarp v4.0.1, BlazinFly v1.8.7, BuilderTools v1.2.0-beta2, PerWorldPlayer v0.1.0, ScoreHud v5.1.1, Clothes v3.1.0, KitUI v1.3.6, BlazinJoin v1.1.6, ZMusicBox v3.1.0, CombatLogger v0.0.6, FormAPI v1.3.0, OnlineTime v1.2, FactionsPro v1.3.20, PureChat v1.4.11, Texter v3.4.7

**Comment by ghost** [comment] 2020-04-27 13:31
I saw in BlazinFly.phar file, permissions section: default is op. I think it may be this.

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 13:36
the default op in plugin.yml sets the default permission requirement for the commands to opped players. You can add the permission to a group since you have PurePerms, do `/setgperm <group name> blazinfly.command` to allow it or `/setgperm <group name> -blazinfly.command` to disallow it.

**Comment by ghost** [comment] 2020-04-27 13:37
I do it that but not function

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 13:39
Send me a picture of the permissions on the group that you are having trouble with, `/listgperms `command in game.

**Comment by ghost** [comment] 2020-04-27 13:44
![prueba 1](https://user-images.githubusercontent.com/64415918/80379100-eca99080-889d-11ea-9354-d404bc38a875.PNG)
![prueba 2](https://user-images.githubusercontent.com/64415918/80379105-ee735400-889d-11ea-8efd-3de226a77291.PNG)

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 13:46
Is your group set to Owner?

**Comment by ghost** [comment] 2020-04-27 13:46
Yes.

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 13:46
Are you opped as well?

**Comment by ghost** [comment] 2020-04-27 13:48
If I tell the truth, I have tried it in different groups, but it does not work in any, unless I have the OP

**Comment by ghost** [comment] 2020-04-27 13:52
I just want do the command /fly without have OP.

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 13:52
Try creating a group called "owner" with a lowercase o instead, I have had trouble in the past with the group Owner and new permissions. If that does not work then truly I do not know what the issue is because it is not with my plugin. I have tested it myself with OP and no OP for each of the two commands.

**Comment by iiFlamiinBlaze** [comment] 2020-04-27 13:55
Also make sure that your plugin is updated to the most recent version, here is the link to download it.

 https://poggit.pmmp.io/r/63356/BlazinFly_dev-15.phar

**Comment by iiFlamiinBlaze** [comment] 2020-04-29 14:11
Im going to close this now, since its resolved.

**Closed as completed by iiFlamiinBlaze** 2020-04-29 14:11 UTC
